/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snakePkg;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JOptionPane;

/**
 * The main window...
 *
 * @author wengc
 */
public class SnakeMainWindow extends javax.swing.JFrame implements KeyListener {

    SnakeDrawer snakeDrawer;
    AppParameters appParameters;
    ExecutorService pool;

    /**
     * Creates new form SnakeMainWindow
     */
    public SnakeMainWindow() {
        appParameters = new AppParameters();
        initComponents();  
        this.snakeDrawer = new SnakeDrawer(appParameters, this.jPanel1);
        this.startNewGame();
    }

    final void startNewGame() {
        if (pool == null) {
            this.pool = Executors.newFixedThreadPool(1);
        }
        this.snakeDrawer.startNewGame();
        this.pool.execute(this.snakeDrawer); 
        //this.pool.submit(snakeDrawer);
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("Shutting down pool.");
            this.pool.shutdownNow();
        }, "Shutdown-thread"));
        this.setFocusable(true); // To make sure the jframe key listener works
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonNewGame = new javax.swing.JButton();
        jToggleButtonPause = new javax.swing.JToggleButton();
        jButtonSpeedX2 = new javax.swing.JButton();
        jButton2jButtonSpeedX0_5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("蛇吃屎 by C.Weng. 19w30, Tuve.");
        setPreferredSize(new java.awt.Dimension(520, 556));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(520, 540));

        jPanel1.setLayout(new java.awt.GridLayout(this.appParameters.gridRows, this.appParameters.gridCols));

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButtonNewGame.setText("New Game (新游戏)");
        jButtonNewGame.setFocusable(false);
        jButtonNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewGameActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNewGame);

        jToggleButtonPause.setText("Pause (暂停)");
        jToggleButtonPause.setFocusable(false);
        jToggleButtonPause.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonPauseStateChanged(evt);
            }
        });
        jPanel2.add(jToggleButtonPause);

        jButtonSpeedX2.setText("Speed X2");
        jButtonSpeedX2.setFocusable(false);
        jButtonSpeedX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeedX2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSpeedX2);

        jButton2jButtonSpeedX0_5.setText("Speed X0.5");
        jButton2jButtonSpeedX0_5.setFocusable(false);
        jButton2jButtonSpeedX0_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2jButtonSpeedX0_5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2jButtonSpeedX0_5);

        jMenu2.setText("About");

        jMenuItem2.setText("About this app...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        this.addKeyListener(this);

        setBounds(0, 0, 587, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonPauseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonPauseStateChanged
        // TODO add your handling code here:
        this.appParameters.isPause = this.jToggleButtonPause.isSelected();    
    }//GEN-LAST:event_jToggleButtonPauseStateChanged

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Made by C.Weng for his wife Huan仔. 19w29, Tuve.");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButtonSpeedX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeedX2ActionPerformed
        // TODO add your handling code here:
        this.appParameters.sleepMilliSecond = Math.round(this.appParameters.sleepMilliSecond/2);
    }//GEN-LAST:event_jButtonSpeedX2ActionPerformed

    private void jButton2jButtonSpeedX0_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2jButtonSpeedX0_5ActionPerformed
        // TODO add your handling code here:
        this.appParameters.sleepMilliSecond = Math.round(this.appParameters.sleepMilliSecond*2);
    }//GEN-LAST:event_jButton2jButtonSpeedX0_5ActionPerformed

    private void jButtonNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewGameActionPerformed
        // TODO add your handling code here:
        if (!this.snakeDrawer.isAlive()){
            this.startNewGame();
        }  
    }//GEN-LAST:event_jButtonNewGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnakeMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SnakeMainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2jButtonSpeedX0_5;
    private javax.swing.JButton jButtonNewGame;
    private javax.swing.JButton jButtonSpeedX2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButtonPause;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent arg0) {
    }

    @Override
    /**
     * Change direction dir: up: [-1, 0] down: [1, 0] left: [0, -1] right: [0,
     * 1] Changing direction in the same axis will be ignored.
     */
    public void keyPressed(KeyEvent arg0) {
        int[] newDir = new int[2];
        int ud = this.snakeDrawer.dir[0];
        int lr = this.snakeDrawer.dir[1];
        if ((arg0.getKeyCode() == KeyEvent.VK_UP || arg0.getKeyCode() == KeyEvent.VK_DOWN) && ud == 0) {
            newDir[1] = 0;
            if (arg0.getKeyCode() == KeyEvent.VK_UP) {
                newDir[0] = -1;
            } else {
                newDir[0] = 1;
            }
        } else if ((arg0.getKeyCode() == KeyEvent.VK_LEFT || arg0.getKeyCode() == KeyEvent.VK_RIGHT) && lr == 0) {
            newDir[0] = 0;
            if (arg0.getKeyCode() == KeyEvent.VK_LEFT) {
                newDir[1] = -1;
            } else {
                newDir[1] = 1;
            }
        }
        // I realize that it is not sufficient to check if the new dir is ok or not by only looking at the dir vector itself.
        if (this.snakeDrawer.isNewDirOk(newDir)){
            this.snakeDrawer.dir = newDir;
        }
    }

    @Override
    public void keyReleased(KeyEvent arg0) {
        if (!this.snakeDrawer.isAlive() && arg0.getKeyCode() == KeyEvent.VK_ENTER){
            this.startNewGame();
        }
    }
}
